resources:
  - name: master
    type: git
    icon: git

    source:
      uri: https://github.com/prashanthbn/SampleApp.git
      branch: develop
      git_config:
        - name: safe.directory
          value: "*"
      ignore_paths:
        - .git/**
        - .git/*
        - .git/
        - .git
        - .gitignore
jobs:
  - name: ci
    plan:
      - get: master
        trigger: true
      - task: build
        privileged: true
        config:
          platform: linux
          inputs:
            - name: master
          image_resource:
            type: docker-image
            source:
              repository: mcr.microsoft.com/dotnet/sdk
              tag: 9.0-noble
          run:
            path: sh
            args:
              - -exc
              - |
                cd ./master
                dotnet restore
                dotnet test
