---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/sdk
    tag: 6.0-jammy

inputs:
- name: code

outputs:
- name: code

run:
  path: sh
  args:
  - -exec
  - |
    chmod u+x code/Pipelines/Scripts/build.sh
    bash code/Pipelines/Scripts/build.sh