---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/sdk
    tag: 6.0-jammy
inputs:
- name: folder

run:
  path: sh
  args:
  - -exec
  - |
    ls