---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/sdk
    tag: 9.0-alpine

inputs:
  - name: built

outputs:
  - name: built

run:
  path: sh
  args:
    - -exec
    - |
      chmod u+x built/Pipeline/Scripts/unit-tests.sh
      bash built/Pipeline/Scripts/unit-tests.sh
