resources:
- name: master
  type: git
  icon: git
  source:
    uri: https://github.com/prashanthbn/SampleApp.git
    branch: develop
    ignore_paths:
      - .git/**
      - .git/*
      - .git/
      - .git
      - .gitignore

- name: sample-api-img
  type: docker-image
  icon: docker
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/sample-api

jobs:

  - name: ci
    serial: true

    plan:

      - get: master
        trigger: true

      #
      # TREE SOURCE CODE - MASTER
      #

      - task: tree-source
        file: master/Pipeline/Tasks/tree.yml
        input_mapping: { folder: master }

      #
      #  BUILD THE SOURCE CODE
      #

      - task: build
        file: master/Pipeline/Tasks/build.yml
        input_mapping: { code: master }
        output_mapping: { code: master }

      #
      # TREE BUILT
      #

      - task: tree-built
        file: master/Pipeline/Tasks/tree.yml
        input_mapping: { folder: master }
      
      #
      # RUN UNIT TESTS
      #

      - task: unit-tests
        file: master/Pipeline/Tasks/unit-tests.yml
        input_mapping: { built: master }
        output_mapping: { built: master }

      
      #
      #  CONTAINERISE
      #

      - put: sample-api-img
        params:
          build: .f
          dockerfile: master/Pipeline/Dockerfile